eureka:
  client:
    service-url:
      defaultZone: http://hr-eureka-server:8761/eureka
  instance:
    instance-id: ${spring.application.name}:{spring.application.instance_id:${random.value}}
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ConnectionTimeout: 10000
  ReadTimeout: 20000

server:
  port: ${PORT:0}

spring:
  application:
    name: hr-payroll
